<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="icons8-broom-70.png" />
    <None Remove="icons8-mise-à-jour-70.png" />
    <None Remove="icons8-nettoyer-70.png" />
    <None Remove="icons8-plan-de-traitement-70.png" />
    <None Remove="icons8-site-internet-70.png" />
    <None Remove="website-icon-29482-Windows.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="icons8-broom-70.png" />
    <Resource Include="icons8-mise-à-jour-70.png" />
    <Resource Include="icons8-plan-de-traitement-70.png" />
    <Resource Include="icons8-site-internet-70.png" />
    <Resource Include="website-icon-29482-Windows.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
