<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="malkha-plat-marocain.jpg" />
    <None Remove="Un-plat-familial-en-sauce-comme-chez-mamie.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="malkha-plat-marocain.jpg" />
    <Resource Include="Un-plat-familial-en-sauce-comme-chez-mamie.jpg" />
  </ItemGroup>

</Project>
